### ISSUE TITLE
API route to get all sensors associated to user that contains plant associated to each sensors

### ISSUE THREAD

**Issue by Sainane** [Plant-keeper/backend#68]
Need
-  On sensor page I need to show all sensors that belong to user and show the plant name associated to the sensor
-  I'd like to be able to make a get request on all user sensors that gives me the associated plant
Problem
-  When I get the sensors on /users/sensors I have no information about associated plants
- I can do a workaround with a second request on all plants and then match ids but it's heavy (and there are two occasions where I need this)
Idea
1.  The  get users/sensors request should respond with all sensors and their associated plant (join on database) by default
2. Create a vue for example, maybe in another route that gives me these informations (id of associated plant + name of associated plant added to the sensors infos)

**Comment by evarayHEIG** [comment]
Pour appuyer le propos, j'insiste sur le fait que c'est pas une demande de changer le schéma de base! On peut en gros résumer ça à un join entre les tables sensors et plants sur sensors.id = plants.sensorId (et éventuellement garder toutes les colonnes de sensors et seulement le name et id de la table plants ). L'outil qu'on utilisait en BDR pour faire ça, c'est des vues, qui peuvent être traitée comme une table quand on parle de requêtes GET. En checkant rapidement, ça existe sur typeORM (https://orkhan.gitbook.io/typeorm/docs/view-entities). 
Du coup, on pourrait y avoir accès par une nouvelle route, ce qui fait qu'il y a pas de route à modifier.

Sinon, pas de vue et juste un join avec des querry isok.

**Comment by evarayHEIG** [comment]
## Pourquoi on ne change pas le sens de la relation sensors 1 --- 0..1 plants

Elle met en avant qu'un sensor peut être lié à aucune ou une plante et donc peut exister tout seul, alors que la plante a absolument besoin d'être associée à un capteur pour exister. Si on met la clé étrangère fans sensors et pas plants, on se retrouve avec une plante qui peut être toute seule perdue dans l'espace car rien ne nous assure qu'un capteur est lié à elle, ce qui n'est pas ce qu'on veut (et ce qui est même faux vu notre utilisation de la database).  De plus, on aimerait utiliser dans la page "Info" la clé étrangère dans plants donc il ne faut pas l'enlever.

### Et si on la met des deux côtés? 

ChatGPT le résume mieux que moi mais en gros, ce qui m'embête le plus, c'est que c'est redondant pour rien parce que  des requêtes SQL toutes simples font le même taff et  ça rajoute des contraintes difficiles et vraiment fastidieuses à maintenir. 

- Redondance et Incohérence :
    Si une clé étrangère est placée des deux côtés de la relation, cela introduit une redondance. Cela signifie que la même information (la relation entre A et B) est stockée à deux endroits différents. Si les valeurs de ces clés étrangères deviennent incohérentes (par exemple, si la clé étrangère de A pointe vers B, mais la clé étrangère de B pointe vers une autre entité A ou reste nulle), cela peut créer des problèmes d'intégrité des données.

- Complexité accrue :
    Gérer des clés étrangères des deux côtés introduit une complexité supplémentaire lors de l'insertion, de la mise à jour ou de la suppression des enregistrements. Il faut s'assurer constamment que les deux clés étrangères sont cohérentes, ce qui nécessite plus de vérifications et peut potentiellement entraîner des erreurs si les contraintes ne sont pas correctement mises en place.

- Conception de base de données relationnelle :
    Dans une relation 1 à 0..1, il est plus efficace et logique de stocker la clé étrangère du côté de l'entité qui peut avoir une référence optionnelle. Par exemple, si une entité A peut exister sans être liée à une entité B (relation 1 à 0..1), alors c'est l'entité B qui devrait avoir une clé étrangère pointant vers A. Cela reflète mieux la nature optionnelle de la relation du côté B.

- Respect des contraintes d'intégrité :
    En plaçant la clé étrangère uniquement du côté où elle est nécessaire (dans ce cas, du côté 0..1), il est plus facile d'appliquer et de maintenir les contraintes d'intégrité référentielle. Cela garantit que la relation entre les deux tables est correcte et que les données restent intègres sans nécessiter des règles de validation supplémentaires.

- Les gens sont tristes:
 Il est dit que si quelqu'un stocke les clés étrangères des deux côtés d'une relation 1 à 0..1, le bonheur moyens des humains baisse et des chatons meurent :/.

**Comment by Sinaf19** [comment]
Des chatons meurent oh nooo :((((
